name: mindflow
description: "FocusFlow - Hebrew-first task management and voice assistant app for users with ADHD"
publish_to: "none"
version: 1.0.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  # Navigation
  go_router: ^14.2.7
  # State Management
  flutter_riverpod: ^2.5.1
  google_fonts: ^6.1.0
  speech_to_text: ^7.0.0
  flutter_tts: ^4.0.2
  sqflite: ^2.0.0
  shared_preferences: ^2.0.0
  http: ^1.0.0
  intl: 0.20.2
  path: ^1.0.0
  path_provider: ^2.1.4
  firebase_core: '>=2.21.1'
  cloud_firestore: '>=5.5.0'
  firebase_auth: ^5.2.0
  firebase_messaging: ^15.1.0
  uuid: ^4.0.0
  google_generative_ai: ^0.4.0
  # Notifications
  flutter_local_notifications: ^17.2.1+2
  # UI Enhancements
  flutter_animate: ^4.5.0
  lottie: ^3.1.2
  shimmer: ^3.0.0
  # Calendar
  table_calendar: ^3.1.0
  # Analytics & Insights
  fl_chart: ^0.68.0
  # Secure Storage
  flutter_secure_storage: ^9.2.2
  # Onboarding
  introduction_screen: ^3.1.12
  # Permission handling
  permission_handler: ^11.3.1
  # Background tasks
  workmanager: ^0.5.2
  # Connectivity
  connectivity_plus: ^6.0.5
  # Package info
  package_info_plus: ^8.0.2
  # Google APIs
  googleapis: ^13.1.0
  googleapis_auth: ^1.6.0
  google_sign_in: ^6.2.1
  # Domain layer
  equatable: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  mockito: ^5.4.4
  build_runner: ^2.4.9

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/images/graphics/
    - assets/images/icons/
    - assets/images/backgrounds/
    - assets/fonts/
    # Main app icons
    - assets/images/logo.jpg
    - assets/images/Icon.jpg
    - assets/images/favicon.jpg
    - assets/images/google_logo.png
    # MindFlow Graphics
    - assets/images/graphics/achieve.png
    - assets/images/graphics/adhd.png
    - assets/images/graphics/flow graphic.png
    - assets/images/graphics/integration.png
    - assets/images/graphics/taskcard.png
    - assets/images/graphics/voiceinputgraphic.png
    # Icons
    - assets/images/icons/ICONSset.png
    - assets/images/icons/mic.png
  
  fonts:
    - family: NotoSansHebrew
      fonts:
        - asset: assets/fonts/NotoSansHebrew-Regular.ttf
        - asset: assets/fonts/NotoSansHebrew-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/NotoSansHebrew-Light.ttf
          weight: 300
        - asset: assets/fonts/NotoSansHebrew-Medium.ttf
          weight: 500
        - asset: assets/fonts/NotoSansHebrew-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/NotoSansHebrew-Bold.ttf
          weight: 700
        - asset: assets/fonts/NotoSansHebrew-Black.ttf
          weight: 900
        - asset: assets/fonts/NotoSansHebrew-VariableFont_wdth,wght.ttf
    - family: NotoSerifHebrew
      fonts:
        - asset: assets/fonts/NotoSerifHebrew-Regular.ttf
        - asset: assets/fonts/NotoSerifHebrew-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/NotoSerifHebrew-Light.ttf
          weight: 300
        - asset: assets/fonts/NotoSerifHebrew-Medium.ttf
          weight: 500
        - asset: assets/fonts/NotoSerifHebrew-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/NotoSerifHebrew-Bold.ttf
          weight: 700
        - asset: assets/fonts/NotoSerifHebrew-Black.ttf
          weight: 900
        - asset: assets/fonts/NotoSerifHebrew-VariableFont_wdth,wght.ttf
