// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBWe_80pDDW4q8qatbtT4YN6u-RNbR3fw8',
    appId: '1:915157123985:web:425c66d080e72680afd030',
    messagingSenderId: '915157123985',
    projectId: 'taskflow-128iw',
    authDomain: 'taskflow-128iw.firebaseapp.com',
    storageBucket: 'taskflow-128iw.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBWe_80pDDW4q8qatbtT4YN6u-RNbR3fw8',
    appId: '1:915157123985:android:425c66d080e72680afd030',
    messagingSenderId: '915157123985',
    projectId: 'taskflow-128iw',
    storageBucket: 'taskflow-128iw.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBWe_80pDDW4q8qatbtT4YN6u-RNbR3fw8',
    appId: '1:915157123985:ios:425c66d080e72680afd030',
    messagingSenderId: '915157123985',
    projectId: 'taskflow-128iw',
    storageBucket: 'taskflow-128iw.firebasestorage.app',
    iosBundleId: 'com.example.mindFlow',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBWe_80pDDW4q8qatbtT4YN6u-RNbR3fw8',
    appId: '1:915157123985:ios:425c66d080e72680afd030',
    messagingSenderId: '915157123985',
    projectId: 'taskflow-128iw',
    storageBucket: 'taskflow-128iw.firebasestorage.app',
    iosBundleId: 'com.example.mindFlow',
  );
}